version: '3.9'
services:
  chatswitch:
    image: kik0220/chatswitch:latest
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]
